# Generated by Django 4.0.3 on 2022-03-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('profession', models.CharField(choices=[('programmer', 'Programmer'), ('designer', 'Designer'), ('manager', 'Manager')], max_length=50)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
    ]
