# Generated by Django 4.0.3 on 2022-03-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='profession',
            field=models.CharField(choices=[('manager', 'Manager'), ('programmer', 'Programmer'), ('designer', 'Designer'), ('quality assurer', 'Quality assurer')], max_length=50),
        ),
    ]
