# Generated by Django 4.0.3 on 2022-03-24 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_homework_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='files',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='files',
        ),
        migrations.RemoveField(
            model_name='homeworktask',
            name='files',
        ),
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, help_text='upload file compressed to zip or rar', null=True, upload_to='courses_files/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])], verbose_name='course file'),
        ),
        migrations.AddField(
            model_name='homework',
            name='file',
            field=models.FileField(blank=True, help_text='upload file compressed to zip or rar', null=True, upload_to='homeworks/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])], verbose_name='homework file'),
        ),
        migrations.AddField(
            model_name='homeworktask',
            name='file',
            field=models.FileField(blank=True, help_text='upload file compressed to zip or rar', null=True, upload_to='homework_tasks/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])], verbose_name='homework task file'),
        ),
    ]
