# Generated by Django 4.0.3 on 2022-03-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0004_remove_course_files_remove_homework_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='homeworktask',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_tasks', to='courses.course'),
        ),
    ]
