# Generated by Django 4.0.3 on 2022-03-27 12:46

from django.db import migrations, models
import django.utils.timezone
from random import randint


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryuser',
            name='unique_token',
        ),
        migrations.AddField(
            model_name='temporaryuser',
            name='verification_code',
            field=models.SmallIntegerField(blank=True, default=randint(10_000, 99_999)),
            preserve_default=False,
        ),
    ]
