# Generated by Django 4.0.3 on 2022-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_short_info_profile_work_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='app_subscription_mode',
            field=models.CharField(choices=[('pro', 'PRO'), ('base', 'BASE')], default='base', max_length=4),
            preserve_default=False,
        ),
    ]
