# Generated by Django 4.0.3 on 2022-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_app_subscription_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_courses_number',
            field=models.SmallIntegerField(default=10),
        ),
    ]
