# Generated by Django 4.0.3 on 2022-03-30 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_profession'),
        ('users', '0005_profile_free_courses_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_management.profession'),
        ),
    ]
