# Generated by Django 4.0.3 on 2022-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appmanagement',
            name='professions',
        ),
        migrations.AlterField(
            model_name='appmanagement',
            name='base_subscription_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appmanagement',
            name='pro_subscription_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
